Update and rename test to test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -2,7 +2,8 @@ name: 01 - Building Blocks
 
 on:
   push:
-  
+    branches:
+      - main
   workflow_dispatch:
 
 jobs:
@@ -15,10 +16,10 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Successful step
+      - name: Fail step
         run: |
-          echo "I will succeed"
-          exit 0
+          echo "I will fail"
+          exit 1
 
       - name: Say goodbye
-        run: echo "Goodbye!"
+        run: echo "Goodbye Guru"
